
// -----------------------/data---------------------
###
GET http://localhost:8080/visitors/yopaaas/data

###
GET http://localhost:8080/visitors/yopaaas/data?name=1&des=1

###
PUT http://localhost:8080/visitors/yopaaas/data
Content-Type: application/json

{
   "name": "yopaaas"
}






// -----------------------/data/Certificate---------------------
###
GET http://localhost:8080/visitors/yopaaas/data/Certificate

###
GET http://localhost:8080/visitors/yopaaas/data/Certificate?_id=RBcIjzHO-IrsU6V7w9kwJ

###
POST http://localhost:8080/visitors/yopaaas/data/Certificate
Content-Type: application/json

{
   "name": "only love",
   "title": "only love can hurt like this",
   "des": "This is the test.",
   "img": "/images/bgg.webp",
   "date": "Mei 15, 2g023",
   "link": "/bglog"
}

###
PUT http://localhost:8080/visitors/yopaaas/data/Certificate?_id=RBcIjzHO-IrsU6V7w9kwJ
Content-Type: application/json

{
   "title": "yopaaasas"
}

###
DELETE http://localhost:8080/visitors/yopaaas/data/Certificate?_id=Qdv5k8jgzZ7PqRVchMS7w







// -----------------------/data/Blog---------------------
###
GET http://localhost:8080/visitors/yopaaas/data/Blog

###
GET http://localhost:8080/visitors/yopaaas/data/Blog?_id=ReWQZfJgWWGdzOrRyFG9D

###
POST http://localhost:8080/visitors/yopaaas/data/Blog
Content-Type: application/json

{
   "name": "only love",
   "title": "only love can hurt like this",
   "des": "This is the test.",
   "img": "/images/bgg.webp",
   "date": "Mei 15, 2g023",
   "link": "/bglog"
}

###
PUT http://localhost:8080/visitors/yopaaas/data/Blog?_id=oTG0258UropwsyT-dWmyA
Content-Type: application/json

{
   "title": "yopaaa",
   "des": "This is the test."
}

###
DELETE http://localhost:8080/visitors/yopaaas/data/Blog?_id=oTG0258UropwsyT-dWmyA








// -----------------------/data/Experience---------------------
###
GET http://localhost:8080/visitors/yopaaas/data/Experience

###
GET http://localhost:8080/visitors/yopaaas/data/Experience?_id=650e6a2d55ada597df36a89e

###
POST http://localhost:8080/visitors/yopaaas/data/Experience
Content-Type: application/json

{
    "name": "x",
    "title": "Biznet ",
    "des": "Internship Network Engineer at Biznet (PT. Supra Primatama Nusantara)",
    "img": "https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/2449d36946f186a2c5189d16071fdcd6.jpg",
    "date": "May 16, 2023 - Aug 16, 2023",
    "link": "https://www.biznetnetworks.com/?page=2%27[0]"
  }


// test put data
###
PUT http://localhost:8080/visitors/yopaaas/data/Experience?_id=Ztl2go3Gd-MYhAXmy6yAy
Content-Type: application/json

{
   "name": "yopaaasaa",
   "title": "this is title"
}

###
DELETE http://localhost:8080/visitors/yopaaas/data/Experience?_id=K2iIKHnyhu6QCTOkcSCVT






// -----------------------/data/Link---------------------
###
GET http://localhost:8080/visitors/yopaaas/data/Link


// test get specific data Link
###
GET http://localhost:8080/visitors/yopaaas/data/Link?_id=dOqmOWZRZc-Qcosr9bq03

// test POST data
###
POST http://localhost:8080/visitors/yopaaas/data/Link
Content-Type: application/json

{
   "name": "test",
   "link": "https://github.com/yopaaa",
   "img": "/images/icon/github.png"
}


// test put data
###
PUT http://localhost:8080/visitors/yopaaas/data/Link?_id=CmM1Iga2VaaYRek8GrLXi
Content-Type: application/json

{
   "name": "yopaaasaa"
}

###
DELETE http://localhost:8080/visitors/yopaaas/data/Link?_id=CmM1Iga2VaaYRek8GrLXi








// -----------------------/data/Skills---------------------
###
GET http://localhost:8080/visitors/yopaaas/data/Skills

###
GET http://localhost:8080/visitors/yopaaas/data/Skills?_id=O0FdQ6ENCbXnR2fJSUB7n

###
POST http://localhost:8080/visitors/yopaaas/data/Skills
Content-Type: application/json

{
   "name": "test",
   "link": "https://github.com/yopaaa",
   "img": "/images/icon/github.png"
}

###
PUT http://localhost:8080/visitors/yopaaas/data/Skills?_id=EuJYUlqLQDkr0Kbueg7HQ
Content-Type: application/json

{
   "name": "yopaaasaa"
}

###
DELETE http://localhost:8080/visitors/yopaaas/data/Skills?_id=73auoeViSHpNGYEoKH0Fm










// test POST data
###
POST http://localhost:8080/anonymous/yopaaas/new
Content-Type: application/json

{
   "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
   "ipAddress": "216.239.38.120",
   "msg": "test"
}
